/*
*   
*/

-- Create a new Schema on your database
CREATE SCHEMA CORE;

create table CORE.CUSTOMERS (
	 ID				INTEGER PRIMARY KEY
	,FIRSTNAME		VARCHAR(50)
	,SURNAME		VARCHAR(50)
	,GENDER			VARCHAR(5)
	,STREET			VARCHAR(100)
	,ZIP			VARCHAR(10)
	,CITY			VARCHAR(100)
);


create table CORE.RETAILER (
	 RETAILER_ID		INTEGER primary key 
	,RETAILER_NAME		VARCHAR(100)
	,RESELLER_TYPE		VARCHAR(100)
	,RESELLER_LEVEL		VARCHAR(2)
	,RESELLER_ADDRESS	VARCHAR(100)
	,ZIP				VARCHAR(10)
	,CITY 				VARCHAR(100)
);


create table CORE.ORDERS (
	 ORDER_ID			VARCHAR(50) primary key 
	,BASKET_ID			VARCHAR(50) 
	,ORDER_DATE			DATE
	,DUE_DATE			DATE 
	,SHIPPMENT_DATE 	DATE 
	,PRODUCT_ID 		INTEGER 
	,QUANTITY			INTEGER 
	,UNIT_PRICE			NUMERIC(8,2)
);


create table CORE.PRODUCTS (
	 PRODUCT_ID			INTEGER primary key 
    ,PRODUCT_TITLE      VARCHAR(100)
    ,CATEGORY           VARCHAR(100)
    ,RATING             NUMERIC(4,2)
    ,REVIEWS            INTEGER 
    ,PRICE              NUMERIC(8,2)
);


create table CORE.RETAILER_PRODUCT (
    product_id        INTEGER 
    ,retailer_id      INTEGER 
);