CREATE SCHEMA LAKE;

CREATE TABLE LAKE.RETAILER_AD_CAMPAIGN_DL (
    RT_AD_H_SK      VARCHAR(100)
    ,RETAILER_ID    INTEGER 
    ,RETAILER_NAME  VARCHAR(100)
    ,CAMPAIGN_ID    INTEGER 
    ,CAMPAIGN_NAME  VARCHAR(500)
    ,CAMPAIGN_BUDGET    DECIMAL(18,2)
    ,START_DATE     DATE 
    ,END_DATE       DATE 
    ,PRODUCT_ID     INTEGER 
    ,PRODUCT_TITLE  VARCHAR(100)
    ,CATEGORY       VARCHAR(100)
    ,MAX_CPC_BID    DECIMAL(18,2)
);


create table LAKE.TRACKING_CAMPAIGN_DL (
    TRACKING_AD_H_SK        VARCHAR(100)
    ,SESSION_ID             VARCHAR(100)
    ,VISITOR_ID             VARCHAR(100)
    ,EVENT_TIMESTAMP_CET    TIMESTAMP
    ,"FORMAT"               VARCHAR(100)
    ,PAGE                   VARCHAR(100)
    ,CAMPAIGN_ID            INTEGER     
    ,PRODUCT_ID             INTEGER
    ,IMPRESSION_ID          VARCHAR(100) 
    ,AD_POSITION            VARCHAR(5) 
    ,AD_MESSAGE_TYPE        VARCHAR(100)
    ,WINNING_BID            DECIMAL(18,2)
    ,BOT                    BOOLEAN 
);

