/*
	DEMO DATA DDL

	This ddl file contains the structure of the database tables for demo identities and addresses. 
	
*/


/*
	DEMO DATA GERMANY
*/
create table DEMO_IDENTITY_GERMANY (
	 ID 			INTEGER PRIMARY KEY
	,FIRSTNAME		VARCHAR(50)
	,SURNAME		VARCHAR(50)
	,GENDER			VARCHAR(5)
);


create table DEMO_ADDRESSES_GERMANY (
	 ID				INTEGER PRIMARY KEY
	,STREET 		VARCHAR(100)
	,ZIP 			VARCHAR(10)
	,CITY 			VARCHAR(100)
);



create table demo_addresses_helper (
	 ID				INTEGER PRIMARY KEY
	,STREET 		VARCHAR(100)
	,ZIP 			VARCHAR(10)
	,CITY 			VARCHAR(100)
);

create table DEMO_IDENTITIES_FULL_GERMANY(
	 ID				INTEGER PRIMARY KEY
	,FIRSTNAME		VARCHAR(50)
	,SURNAME		VARCHAR(50)
	,GENDER			VARCHAR(5)
	,STREET			VARCHAR(100)
	,ZIP			VARCHAR(10)
	,CITY			VARCHAR(100)
);